namespace XiloAdventures.Engine.Models.Enums;

/// <summary>
/// Identificadores únicos para cada tipo de nodo en el editor de scripts.
/// </summary>
public enum NodeTypeId
{
    #region Event Nodes

    Event_OnGameStart,
    Event_OnGameEnd,
    Event_EveryMinute,
    Event_EveryHour,
    Event_OnTurnStart,
    Event_OnWeatherChange,
    Event_OnEnter,
    Event_OnExit,
    Event_OnLook,
    Event_OnDoorOpen,
    Event_OnDoorClose,
    Event_OnDoorLock,
    Event_OnDoorUnlock,
    Event_OnTalk,
    Event_OnNpcAttack,
    Event_OnNpcDeath,
    Event_OnNpcSee,
    Event_OnCombatStart,
    Event_OnCombatVictory,
    Event_OnCombatDefeat,
    Event_OnCombatFlee,
    Event_OnPlayerAttack,
    Event_OnNpcTurn,
    Event_OnPlayerDefend,
    Event_OnCriticalHit,
    Event_OnMiss,
    Event_OnTradeStart,
    Event_OnTradeEnd,
    Event_OnItemBought,
    Event_OnItemSold,
    Event_OnTake,
    Event_OnDrop,
    Event_OnUse,
    Event_OnGive,
    Event_OnEquip,
    Event_OnUnequip,
    Event_OnExamine,
    Event_OnRead,
    Event_OnContainerOpen,
    Event_OnContainerClose,
    Event_OnEat,
    Event_OnDrink,
    Event_OnSleep,
    Event_OnWakeUp,
    Event_OnWakeUpStartled,
    Event_OnQuestStart,
    Event_OnQuestComplete,
    Event_OnQuestFail,
    Event_OnObjectiveComplete,
    Event_OnPlayerDeath,
    Event_OnHealthLow,
    Event_OnHealthCritical,
    Event_OnHungerHigh,
    Event_OnThirstHigh,
    Event_OnEnergyLow,
    Event_OnSleepHigh,
    Event_OnSanityLow,
    Event_OnManaLow,
    Event_OnStateThreshold,
    Event_OnModifierApplied,
    Event_OnModifierExpired,
    Event_OnMoneyGained,
    Event_OnMoneyLost,
    Event_OnMoneyThreshold,
    Event_OnPropertyChanged,

    #endregion

    #region Condition Nodes

    Condition_HasFlag,
    Condition_HasItem,
    Condition_IsInRoom,
    Condition_IsTimeOfDay,
    Condition_IsWeather,
    Condition_Random,
    Condition_CompareCounter,
    Condition_PlayerOwnsItem,
    Condition_NpcInRoom,
    Condition_ObjectInRoom,
    Condition_ObjectInContainer,
    Condition_IsDoorOpen,
    Condition_IsDoorVisible,
    Condition_IsContainerOpen,
    Condition_IsContainerLocked,
    Condition_IsNpcAlive,
    Condition_IsNpcVisible,
    Condition_IsFollowingPlayer,
    Condition_IsPatrolling,
    Condition_IsInCombat,
    Condition_IsCombatRound,
    Condition_IsInTrade,
    Condition_PlayerHasMoney,
    Condition_NpcHasMoney,
    Condition_NpcHasInfiniteMoney,
    Condition_IsPlayerAlive,
    Condition_PlayerHealthAbove,
    Condition_PlayerHealthBelow,
    Condition_NpcHealthBelow,
    Condition_IsObjectVisible,
    Condition_IsObjectTakeable,
    Condition_IsObjectLit,
    Condition_IsRoomLit,
    Condition_PlayerHasWeaponType,
    Condition_PlayerHasArmor,
    Condition_PlayerHasEquipped,
    Condition_NpcHasEquipped,
    Condition_IsPlayerSlotEmpty,
    Condition_IsNpcSlotEmpty,
    Condition_NpcHasItem,
    Condition_PlayerStateAbove,
    Condition_PlayerStateBelow,
    Condition_PlayerStateBetween,
    Condition_PlayerStateEquals,
    Condition_HasModifier,
    Condition_HasModifierForState,
    Condition_IsQuestStatus,
    Condition_IsMainQuest,
    Condition_CompareProperty,

    #endregion

    #region Action Nodes

    Action_ShowMessage,
    Action_SetFlag,
    Action_SetCounter,
    Action_IncrementCounter,
    Action_TeleportPlayer,
    Action_MoveObjectToRoom,
    Action_GiveItem,
    Action_RemoveItem,
    Action_SetObjectVisible,
    Action_SetObjectTakeable,
    Action_OpenDoor,
    Action_CloseDoor,
    Action_LockDoor,
    Action_UnlockDoor,
    Action_SetDoorVisible,
    Action_OpenContainer,
    Action_CloseContainer,
    Action_LockContainer,
    Action_UnlockContainer,
    Action_PutObjectInContainer,
    Action_RemoveObjectFromContainer,
    Action_SetContentsVisible,
    Action_StartConversation,
    Action_SetRoomDescription,
    Action_SetRoomIllumination,
    Action_SetRoomMusic,
    Action_MoveNpc,
    Action_SetNpcVisible,
    Action_KillNpc,
    Action_ReviveNpc,
    Action_AddNpcItem,
    Action_RemoveNpcItem,
    Action_AddItemToNpcInventory,
    Action_RemoveItemFromNpcInventory,
    Action_EquipPlayerItem,
    Action_UnequipPlayerSlot,
    Action_EquipNpcItem,
    Action_UnequipNpcSlot,
    Action_SetNpcMoney,
    Action_FollowPlayer,
    Action_StopFollowing,
    Action_SetFollowMode,
    Action_StartPatrol,
    Action_StopPatrol,
    Action_SetPatrolRoute,
    Action_SetPatrolMode,
    Action_PatrolStep,
    Action_PlaySound,
    Action_AddPlayerMoney,
    Action_RemovePlayerMoney,
    Action_AddMoney,
    Action_RemoveMoney,
    Action_SetWeather,
    Action_AdvanceTime,
    Action_SetGameHour,
    Action_SetPlayerState,
    Action_ModifyPlayerState,
    Action_FeedPlayer,
    Action_HydratePlayer,
    Action_RestPlayer,
    Action_HealPlayer,
    Action_DamagePlayer,
    Action_RestoreAllStats,
    Action_SetPlayerMaxHealth,
    Action_ConsumeMana,
    Action_RestoreMana,
    Action_ApplyModifier,
    Action_RemoveModifier,
    Action_RemoveModifiersByState,
    Action_RemoveAllModifiers,
    Action_ProcessModifiers,
    Action_AddAbility,
    Action_RemoveAbility,
    Action_AddAbilityToNpc,
    Action_RemoveAbilityFromNpc,
    Action_StartCombat,
    Action_EndCombatVictory,
    Action_EndCombatDefeat,
    Action_ForceFlee,
    Action_HealNpc,
    Action_DamageNpc,
    Action_SetNpcMaxHealth,
    Action_SetNpcAttack,
    Action_SetNpcDefense,
    Action_SetObjectPrice,
    Action_SetObjectDurability,
    Action_SetObjectLit,
    Action_SetLightTurns,
    Action_OpenTrade,
    Action_CloseTrade,
    Action_SetBuyMultiplier,
    Action_SetSellMultiplier,
    Action_StartQuest,
    Action_CompleteQuest,
    Action_FailQuest,
    Action_AdvanceObjective,
    Action_SetQuestStatus,
    Action_SetProperty,
    Action_ModifyProperty,
    Action_SetNeedRate,

    #endregion

    #region Flow Nodes

    Flow_Branch,
    Flow_Sequence,
    Flow_Delay,
    Flow_RandomBranch,

    #endregion

    #region Variable Nodes

    Variable_ConstantBool,
    Variable_ConstantInt,
    Variable_GetFlag,
    Variable_GetCounter,
    Variable_GetCurrentRoom,
    Variable_GetCurrentWeather,
    Variable_GetGameHour,
    Variable_GetPlayerMoney,
    Variable_GetPlayerHealth,
    Variable_GetPlayerMaxHealth,
    Variable_GetPlayerEnergy,
    Variable_GetPlayerMana,
    Variable_GetPlayerMaxMana,
    Variable_GetPlayerHunger,
    Variable_GetPlayerThirst,
    Variable_GetPlayerSleep,
    Variable_GetPlayerSanity,
    Variable_GetPlayerState,
    Variable_HasModifier,
    Variable_GetActiveModifiersCount,
    Variable_GetPlayerStrength,
    Variable_GetPlayerConstitution,
    Variable_GetPlayerIntelligence,
    Variable_GetPlayerDexterity,
    Variable_GetPlayerCharisma,
    Variable_GetPlayerAge,
    Variable_GetPlayerHeight,
    Variable_GetPlayerWeight,
    Variable_GetPlayerInitialMoney,
    Variable_GetProperty,
    Variable_GetNeedRate,

    #endregion

    #region Comparison Nodes

    Compare_Int,
    Compare_Counter,
    Compare_PlayerMoney,

    #endregion

    #region Math Nodes

    Math_Add,
    Math_Subtract,
    Math_Multiply,
    Math_Divide,
    Math_Modulo,
    Math_Negate,
    Math_Abs,
    Math_Min,
    Math_Max,
    Math_Clamp,
    Math_Random,

    #endregion

    #region Logic Nodes

    Logic_And,
    Logic_Or,
    Logic_Not,
    Logic_Xor,

    #endregion

    #region Selection Nodes

    Select_Bool,
    Select_Int,

    #endregion

    #region Conversation Nodes

    Conversation_Start,
    Conversation_End,
    Conversation_NpcSay,
    Conversation_PlayerChoice,
    Conversation_Branch,
    Conversation_Action,
    Conversation_Shop,
    Conversation_BuyItem,
    Conversation_SellItem

    #endregion
}
